services:
  backend:
    build: ./backend
    container_name: elms-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: elms-frontend
    ports:
      - "3000:80"   # ✅ FIX HERE
    depends_on:
      - backend
    restart: unless-stopped
